



    services:
  - type: web
    name: word-video-system
    env: docker
    buildCommand: |
      mkdir -p tmp
      chmod -R 777 tmp
    startCommand: apache2-foreground
    envVars:
      - key: PORT
        value: 10000
    plan: free